<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_d_s_l_r' => [[], ['_controller' => 'App\\Controller\\DSLRController::index'], [], [['text', '/']], [], [], []],
];
