<?php

namespace ContainerCo1omHB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShootingRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ShootingRepository' shared autowired service.
     *
     * @return \App\Repository\ShootingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ShootingRepository'] = new \App\Repository\ShootingRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
