<?php

namespace Container4EbycIi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShootingDuplicationCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ShootingDuplicationCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ShootingDuplicationCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:shooting-duplication', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\ShootingDuplicationCommand')] function () use ($container): \App\Command\ShootingDuplicationCommand {
            return ($container->privates['App\\Command\\ShootingDuplicationCommand'] ?? $container->load('getShootingDuplicationCommandService'));
        });
    }
}
