<?php

namespace Container1EdrRJ3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShootingDuplicationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ShootingDuplicationCommand' shared autowired service.
     *
     * @return \App\Command\ShootingDuplicationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ShootingDuplicationCommand.php';

        $container->privates['App\\Command\\ShootingDuplicationCommand'] = $instance = new \App\Command\ShootingDuplicationCommand();

        $instance->setName('app:shooting-duplication');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
