<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4EbycIi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4EbycIi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4EbycIi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4EbycIi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4EbycIi\App_KernelDevDebugContainer([
    'container.build_hash' => '4EbycIi',
    'container.build_id' => '4c0bb402',
    'container.build_time' => 1674483141,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4EbycIi');
