<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_d_s_l_r' => [[], ['_controller' => 'App\\Controller\\DSLRController::index'], [], [['text', '/']], [], [], []],
    'download_filename' => [['filename'], ['_controller' => 'App\\Controller\\DSLRController::download'], [], [['variable', '/', '[^/]++', 'filename', true], ['text', '/download']], [], [], []],
    'link_photo' => [['code'], ['_controller' => 'App\\Controller\\DSLRController::link_photo'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/photos']], [], [], []],
    'shooting' => [[], ['_controller' => 'App\\Controller\\DSLRController::shooting'], [], [['text', '/shooting']], [], [], []],
];
